### ISSUE TITLE
Build without speedups

### ISSUE THREAD

**Issue by aabdnn** [mitsuhiko/markupsafe#26]
I've been building MarkupSafe using the --without-speedups option, because I have a requirement to distribute this module across various OSes in my network. All, of a sudden, I now see that this option is no longer available for setup.py. How can I build a pure-python setup without building the C extension, for distribution, as I previously did?

**Comment by hkst** [comment]
I am trying to install MarkSafe by calling run_setup ( distutils) and getting "NameError: global name 'BuildFailed' is not defined". 
I can see BuildFailed class in setup.py but not sure why it is failing to call it...

**Comment by gtback** [comment]
+1. This would help work around the problem I'm seeing in babun/babun#315 (granted, there are a lot of layers between babun and markupsafe), but having the --without-speedups option would get me part of the way there.

**Comment by nir0s** [comment]
+1. I kinda want port http://github.com/nir0s/serv for all linux distros and this is the only compiled extension I have...

**Comment by aabdnn** [comment]
I've been waiting forever for the author to reply about this but there's
been no response.

In the meantime, for my own wheels, I build them like this:

CC=/bin/false pip wheel MarkupSafe

This makes pip think that there's no C compiler available and builds a
portable wheel.
